/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_project;

import Global_Sources.Dbconnect;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author PRASAD
 */
public class AddEditRemoveSuppliers extends javax.swing.JFrame {
    
    Dbconnect db1 = new Dbconnect();
    Connection con1 = db1.connect();

    /**
     * Creates new form Sub_Interface
     */
    public AddEditRemoveSuppliers() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    
//        if(Data.Login.getPre_UI_type()==1 || Data.Login.getPre_UI_type()==2 )
//        {
//          animation_Start a = new animation_Start(getWidth(), getHeight());
//          setVisible(true);
//          a.start();
//        }
        
        //set supplier id
        
        this.txtSuppID.setText(getSupplierID());
        
        //load edit supplier list
        
        loadEditSupplierList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSuppID = new javax.swing.JTextField();
        txtSuppName = new javax.swing.JTextField();
        txtSuppOtherName = new javax.swing.JTextField();
        txtSupMoble = new javax.swing.JTextField();
        txtSuppOffice = new javax.swing.JTextField();
        txtSuppEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSuppAddr = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        benClear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cmbSupp = new javax.swing.JComboBox();
        btnGetDetails = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEditSupp = new javax.swing.JButton();
        btnDelSupp = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Serial NO");

        jLabel6.setText("Commissioned date  ");

        jLabel7.setText("Delivered  time ");

        jLabel8.setText("Genset Model");

        jLabel9.setText("Genset S/N");

        jLabel14.setText("Controller Type");

        jLabel15.setText("Environment");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Edit Remove Suppliers");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(252, 252, 252));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Supplier ID");

        jLabel3.setText("Supplier Name");

        jLabel4.setText("Contact No ( Mobile )");

        jLabel5.setText("email");

        jLabel10.setText("Address");

        jLabel11.setText("Contact No ( Office )");

        jLabel12.setText("Other Name");

        txtSuppID.setEditable(false);
        txtSuppID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtSuppName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtSuppOtherName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtSupMoble.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtSuppOffice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtSuppEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtSuppAddr.setColumns(20);
        txtSuppAddr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSuppAddr.setRows(5);
        jScrollPane1.setViewportView(txtSuppAddr);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        benClear.setText("Clear");
        benClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benClearActionPerformed(evt);
            }
        });

        jButton1.setText("DEMO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(56, 56, 56)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSuppName, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(txtSuppOtherName)
                    .addComponent(txtSupMoble, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppEmail)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(benClear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(99, 99, 99))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSuppID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppOtherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupMoble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuppEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(benClear)
                    .addComponent(jButton1))
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Add Supplier", jPanel8);

        jPanel9.setBackground(new java.awt.Color(252, 252, 252));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Select Supplier");

        cmbSupp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGetDetails.setText("Get Details");
        btnGetDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDetailsActionPerformed(evt);
            }
        });

        jLabel16.setText("Supplier ID");

        jLabel17.setText("Supplier Name");

        jLabel18.setText("Other Names");

        jLabel19.setText("Contanct No ( Mobile )");

        jLabel20.setText("Contact No ( Office ) ");

        jLabel21.setText("email");

        jLabel22.setText("Address");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        btnEditSupp.setText("Edit Supplier");
        btnEditSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSuppActionPerformed(evt);
            }
        });

        btnDelSupp.setText("Delete Supplier");
        btnDelSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelSuppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cmbSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnGetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btnEditSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(btnDelSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetDetails))
                .addGap(50, 50, 50)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditSupp)
                    .addComponent(btnDelSupp))
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Edit / Remove Supplier", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     class animation_Start extends Thread {

        int max_w;
        int max_h;

        public animation_Start(int max_w, int max_h) {
            this.max_h = max_h;
            this.max_w = max_w;
        }
        long sleepb = 1;
        int add = 30;//no pixels add

        public void run() {
            setSize(0, 0);
            int x = 0;
            int y = 0;

            while (y < max_h || x < max_w) {
                if (y > max_h && x < max_w) {
                    x = x + add;
                    setSize(x, max_h);
                } else if (y < max_h && x > max_w) {

                    y = y + add;
                    setSize(max_w, y);
                } else if (y < max_h && x < max_w) {
                    y = y + add;
                    x = x + add;
                    setSize(x, y);
                } else//window has got the wanted size(prefered size)
                {
                    setSize(max_h, max_w);
                    pack();
                }



                try {
                    sleep(sleepb);
                } catch (InterruptedException ex) {
                    
                }

            }
            //  setSize(962, 697);
            pack();
           // System.out.println(getWidth());
            //System.out.println(getHeight());

        }
    }
    //animation for exit of window
    class animation_exit extends Thread {

        long sleepa = 1;
        int min =25;//no pixels reduce

        public void run() {
            int x = getWidth();
            int y = getHeight();

            while (x > 0 || y > 0) {
                x = x - min;
                y = y - min;
                setSize(x, y);
                try {
                    sleep(sleepa);
                } catch (InterruptedException ex) {
                    
                }

            }

        }
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        Color normal=new Color(255, 255, 255);//white normal colour
        Color error=new Color(255, 255, 153);
        this.txtSuppName.setBackground(normal);
        this.txtSupMoble.setBackground(normal);
        this.txtSuppOffice.setBackground(normal);
        this.txtSuppAddr.setBackground(normal);
        
        String ID = this.txtSuppID.getText();
        String sName = this.txtSuppName.getText() ;
        String oName = this.txtSuppOtherName.getText() ;
        String mobile = this.txtSupMoble.getText();
        String office = this.txtSuppOffice.getText();
        String email = this.txtSuppEmail.getText() ;
        String address = this.txtSuppAddr.getText() ;
        
        if(sName.equals("") || office.equals("") || mobile.equals("") || address.equals(""))
        {
            this.txtSuppName.setBackground(error);
            this.txtSupMoble.setBackground(error);
            this.txtSuppOffice.setBackground(error);
            this.txtSuppAddr.setBackground(error);
            
            JOptionPane.showMessageDialog(this,"Highlighted Entries must be filled", "METROPOLITAN ENGINEERING (PVT) LTD", 2);
        }
        else
        {
            Pattern pattern = Pattern.compile("\\d{10}");
            Matcher matcher1 = pattern.matcher(mobile);
            Matcher matcher2 = pattern.matcher(office);
            if(matcher1.matches() && matcher2.matches())
            {
                
                System.out.println("Correct");
                
                int x1=0;
           
           
           PreparedStatement stmt1 = null;
           
           try{
           stmt1 = con1.prepareStatement("INSERT INTO supplier values(?, ?, ?, ?, ?, ?, ?)");
           stmt1.setString(1, ID);
           stmt1.setString(2, sName);
           stmt1.setString(3, oName);
           stmt1.setString(4, mobile);
           stmt1.setString(5, office);
           stmt1.setString(6, email);
           stmt1.setString(7, address);
           x1 = stmt1.executeUpdate();
           
           
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }
           
        
          if(x1>0)
              JOptionPane.showMessageDialog(null, "Records inserted sucessfully! ","METROPOLITAN ENGINEERING (PVT) LTD", 1);
           else
               JOptionPane.showMessageDialog(null, "Error in Database. Please Reconnect! ","METROPOLITAN ENGINEERING (PVT) LTD", 1);
      
            }
            else
            {
                this.txtSupMoble.setBackground(error);
                this.txtSuppOffice.setBackground(error);
                
                JOptionPane.showMessageDialog(this,"Invalid Phone number Format!", "METROPOLITAN ENGINEERING (PVT) LTD", 2);
            }
        }
        
        
        
        this.txtSuppID.setText(getSupplierID());
        
        this.txtSuppID.setText(getSupplierID());
        this.txtSuppName.setText("") ;
        this.txtSuppOtherName.setText("") ;
        this.txtSupMoble.setText("");
        this.txtSuppOffice.setText("");
        this.txtSuppEmail.setText("") ;
        this.txtSuppAddr.setText("") ;
        loadEditSupplierList();
    }//GEN-LAST:event_btnAddActionPerformed

    public String getSupplierID()
    {
        String gen = "select count(*) as 'field' from supplier";
   
        int n1=1;
      
        
        ResultSet count1 = db1.executeSQLQuery(gen);
        
        try
        {
            if(count1.next())
            {
                n1 += Integer.parseInt(count1.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        
        return ("Supplier"+Integer.toString(n1));
    }
      
    private void benClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benClearActionPerformed
        // TODO add your handling code here:
        
        this.txtSuppID.setText(getSupplierID());
        this.txtSuppName.setText("") ;
        this.txtSuppOtherName.setText("") ;
        this.txtSupMoble.setText("");
        this.txtSuppOffice.setText("");
        this.txtSuppEmail.setText("") ;
        this.txtSuppAddr.setText("") ;
    }//GEN-LAST:event_benClearActionPerformed

    private void btnEditSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSuppActionPerformed
        // TODO add your handling code here:
        
        Color normal=new Color(255, 255, 255);//white normal colour
        Color error=new Color(255, 255, 153);
        this.jTextField2.setBackground(normal);
        this.jTextField4.setBackground(normal);
        this.jTextField2.setBackground(normal);
        this.jTextArea1.setBackground(normal);
        
        
        
         // supplier variables
        
        String sName = this.jTextField2.getText();
        String sOtherName = this.jTextField3.getText();
        String mobile  = this.jTextField4.getText();
        String office = this.jTextField5.getText();
        String sEmail = this.jTextField6.getText();
        String address = this.jTextArea1.getText();
        
        if(sName.equals("") || office.equals("") || mobile.equals("") || address.equals(""))
        {
            this.jTextField2.setBackground(error);
            this.jTextField4.setBackground(error);
            this.jTextField5.setBackground(error);
            this.jTextArea1.setBackground(error);
            
            JOptionPane.showMessageDialog(this,"Highlighted Entries must be filled", "METROPOLITAN ENGINEERING (PVT) LTD", 2);
        }
        else
        {
            Pattern pattern = Pattern.compile("\\d{10}");
            Matcher matcher1 = pattern.matcher(mobile);
            Matcher matcher2 = pattern.matcher(office);
            if(matcher1.matches() && matcher2.matches())
            {
                
               PreparedStatement stmt1 = null;
       
       
            int x1=0;
           
           try
           {
   
           stmt1 = con1.prepareStatement("update supplier set sName=? , sOtherName=?, sMobile=? , sOffice=? , sEmail=? , sAddress=?  where sID='"+this.jTextField1.getText().toString()+"'");
          
           stmt1.setString(1, sName);
           stmt1.setString(2, sOtherName);
           stmt1.setString(3, mobile);
           stmt1.setString(4, office);
           stmt1.setString(5, sEmail);
           stmt1.setString(6, address);
           
   
           x1 = stmt1.executeUpdate();
           
          
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }
       
           
        
          if(x1>0)
              JOptionPane.showMessageDialog(null, "Records updated sucessfully! ","METROPOLITAN ENGINEERING (PVT) LTD", 1);
           else
               JOptionPane.showMessageDialog(null, "Error in Database. Please Reconnect! ","METROPOLITAN ENGINEERING (PVT) LTD", 1);
       
      
            }
            else
            {
                this.jTextField4.setBackground(error);
                this.jTextField5.setBackground(error);
                
                JOptionPane.showMessageDialog(this,"Invalid Phone number Format!", "METROPOLITAN ENGINEERING (PVT) LTD", 2);
            }
        }
        
       /* 
        
       */ 
        loadEditSupplierList();
    }//GEN-LAST:event_btnEditSuppActionPerformed

    private void btnGetDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDetailsActionPerformed
        // TODO add your handling code here:
        
        String selected = this.cmbSupp.getSelectedItem().toString();
        
        String gen = "select * from supplier where sName = '"+selected+"'";
       
        
        ResultSet result1= db1.executeSQLQuery(gen);
        
        
        try
        {
        while(result1.next())
        {
            this.jTextField1.setText(result1.getString("sID"));
            this.jTextField2.setText(result1.getString("sName"));
            this.jTextField3.setText(result1.getString("sOtherName"));
            this.jTextField4.setText(result1.getString("sMobile"));
            this.jTextField5.setText(result1.getString("sOffice"));
            this.jTextField6.setText(result1.getString("sEmail"));
            this.jTextArea1.setText(result1.getString("sAddress"));
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
    }//GEN-LAST:event_btnGetDetailsActionPerformed

    private void btnDelSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelSuppActionPerformed
        // TODO add your handling code here:
        
        int x=JOptionPane.showConfirmDialog(null,"Are you sure you want to delete this Supplier?",
            "METROPOLITAN ENGINEERING (PVT) LTD",0,3 );
       
       if(x==0)
       {
        
        int x1 = 0;
           try{
           
           String gen = this.jTextField1.getText().toString();
               
           PreparedStatement stmt1 = null;
           
           
           
           
           stmt1 = con1.prepareStatement("update supplier set sName='deleted' where sID=? ");
           stmt1.setString(1, gen);
           x1 = stmt1.executeUpdate();
           
           
           
           }
           catch(Exception e)
           {
               System.out.println(e.getMessage());
           }
       
           
        
          if(x1>0 )
          {
              JOptionPane.showMessageDialog(null, "Record deleted sucessfully! ","METROPOLITAN ENGINEERING (PVT) LTD", 1);
              
               loadEditSupplierList();
               
         
          }
           else
               JOptionPane.showMessageDialog(null, "Error in Database. Please Reconnect! ","METROPOLITAN ENGINEERING (PVT) LTD", 1);
       }
       
       else
       {
           JOptionPane.showMessageDialog(null, "Delete process ABORTED!","METROPOLITAN ENGINEERING (PVT) LTD", 1);
       }
       
       loadEditSupplierList();
    }//GEN-LAST:event_btnDelSuppActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        if (Data.Login.getPre_UI_type() == 1 || Data.Login.getPre_UI_type() == 2) {
            animation_exit a = new animation_exit();
            a.start();
            try {
                a.join();
            } catch (InterruptedException ex) {
                
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //String ID = this.txtSuppID.getText();
        this.txtSuppName.setText("Nemo Engineering") ;
        this.txtSuppOtherName.setText("Nemo") ;
        this.txtSupMoble.setText("0756826381");
        this.txtSuppOffice.setText("0115684393");
        this.txtSuppEmail.setText("nemo@gmail.com") ;
        this.txtSuppAddr.setText("No:65 \nWerawaththa Road,\nColombo") ;
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void loadEditSupplierList()
    {
        this.cmbSupp.removeAllItems();
        
        String proList = "select sName as 'field' from supplier where sName != 'deleted'";
   
        
      
        
        ResultSet countList = db1.executeSQLQuery(proList);
        
        try
        {
            while(countList.next())
            {
                //n1 += Integer.parseInt(count1.getString("field"));
                this.cmbSupp.addItem(countList.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditRemoveSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditRemoveSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditRemoveSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditRemoveSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditRemoveSuppliers().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton benClear;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelSupp;
    private javax.swing.JButton btnEditSupp;
    private javax.swing.JButton btnGetDetails;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbSupp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtSupMoble;
    private javax.swing.JTextArea txtSuppAddr;
    private javax.swing.JTextField txtSuppEmail;
    private javax.swing.JTextField txtSuppID;
    private javax.swing.JTextField txtSuppName;
    private javax.swing.JTextField txtSuppOffice;
    private javax.swing.JTextField txtSuppOtherName;
    // End of variables declaration//GEN-END:variables
}
