/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_project;

import GUI_Product.AddEditRemoveProducts;
import Global_Sources.Dbconnect;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PRASAD
 */
public class InterfaceProject extends javax.swing.JFrame {

     Dbconnect db1 = new Dbconnect();
    Connection con1 = db1.connect();
    boolean status;
    
    String t1 = "";
    String t2 = "";
    String t3 = "";
    String m1 = "";
    String m2 = "";
    String m3 = "";
    
    
    
    /**
     * Creates new form Sub_Interface
     */
    public InterfaceProject() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        status=true;
        
//        if(Data.Login.getPre_UI_type()==1 || Data.Login.getPre_UI_type()==2 )
//        {
//          animation_Start a = new animation_Start(getWidth(), getHeight());
//          setVisible(true);
//          a.start();
//        }
        
        Threadd dd = new Threadd();
        dd.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Serial NO");

        jLabel6.setText("Commissioned date  ");

        jLabel7.setText("Delivered  time ");

        jLabel8.setText("Genset Model");

        jLabel9.setText("Genset S/N");

        jLabel14.setText("Controller Type");

        jLabel15.setText("Environment");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(248, 248, 248));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(252, 252, 252));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/proPanel.jpg"))); // NOI18N
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 470, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageProjects.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 394, 185, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manageSuppliers.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 394, 190, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MarkProjects.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 396, 180, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchProject.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 460, 170, 50));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/viewProjects.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 168, 50));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pending projects :");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 111, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("...");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 111, 83, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Finished projects :");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 152, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("...");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 152, 65, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("This week projects :");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 193, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("...");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 193, 65, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Next week projects :");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 234, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("...");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 234, 83, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("This month projects : ");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 275, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("...");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 275, 65, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Next month projects : ");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
        });
        jLabel19.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jLabel19ComponentRemoved(evt);
            }
        });
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 316, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("...");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 316, 65, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 240, 120, 40));

        jButton7.setText("View Next Month Projects");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 312, 164, -1));

        jButton8.setText("View This Month Projects");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 271, 164, -1));

        jButton9.setText("Vsiew Next Week Project");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 230, 164, -1));

        jButton10.setText("View This Week Projects");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 189, 164, -1));

        jButton11.setText("View Fnished Projects");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 148, 164, -1));

        jButton12.setText("View Pending Projects");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 107, 164, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("...");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 270, -1));

        jButton13.setText("Products");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 530));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper3.png"))); // NOI18N
        jLabel24.setAlignmentY(0.0F);
        jLabel24.setMinimumSize(new java.awt.Dimension(812, 512));
        jLabel24.setPreferredSize(new java.awt.Dimension(812, 512));
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class animation_Start extends Thread {

        int max_w;
        int max_h;

        public animation_Start(int max_w, int max_h) {
            this.max_h = max_h;
            this.max_w = max_w;
        }
        long sleepb = 1;
        int add = 30;//no pixels add

        public void run() {
            setSize(0, 0);
            int x = 0;
            int y = 0;

            while (y < max_h || x < max_w) {
                if (y > max_h && x < max_w) {
                    x = x + add;
                    setSize(x, max_h);
                } else if (y < max_h && x > max_w) {

                    y = y + add;
                    setSize(max_w, y);
                } else if (y < max_h && x < max_w) {
                    y = y + add;
                    x = x + add;
                    setSize(x, y);
                } else//window has got the wanted size(prefered size)
                {
                    setSize(max_h, max_w);
                    pack();
                }



                try {
                    sleep(sleepb);
                } catch (InterruptedException ex) {
                    
                }

            }
            //  setSize(962, 697);
            pack();
           // System.out.println(getWidth());
            //System.out.println(getHeight());

        }
    }
    //animation for exit of window
    class animation_exit extends Thread {

        long sleepa = 1;
        int min =25;//no pixels reduce

        public void run() {
            int x = getWidth();
            int y = getHeight();

            while (x > 0 || y > 0) {
                x = x - min;
                y = y - min;
                setSize(x, y);
                try {
                    sleep(sleepa);
                } catch (InterruptedException ex) {
                    
                }

            }

        }
    }
    
    public class Threadd extends Thread 
    {
    
    @Override
    public void run()
    {
        
        while(true)
        {
            if(status)
            {
            Calendar calendar1 = new GregorianCalendar();
          calendar1.add(Calendar.SECOND, 120);
          jLabel21.setText("Next Automatic Update @ "+ Integer.toString(calendar1.getTime().getHours())+ " : " + Integer.toString(calendar1.getTime().getMinutes()) + " : " + Integer.toString(calendar1.getTime().getSeconds()) );
                
        String gene = "select count(*) as 'field' from project where pStatus='pending' and pAvailability='YES'";
   
        int num=0;
      
        
        ResultSet count13 = db1.executeSQLQuery(gene);
        
        try
        {
            if(count13.next())
            {
                num += Integer.parseInt(count13.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        jLabel4.setText(Integer.toString(num));
        
        
        //get finished jobs
        
        String gene1 = "select count(*) as 'field' from project where pStatus='finished' and pAvailability='YES'";
   
        int num1=0;
      
        
        ResultSet count1 = db1.executeSQLQuery(gene1);
        
        try
        {
            if(count1.next())
            {
                num1 += Integer.parseInt(count1.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        jLabel10.setText(Integer.toString(num1));
        
        
        //this week projects
        
        Calendar today = new GregorianCalendar();
        
        
        String todayYear = Integer.toString(today.get(Calendar.YEAR));
        String todayMonth = Integer.toString(today.get(Calendar.MONTH)+1);
        String todayDate = Integer.toString(today.get(Calendar.DATE));
        
        String todayy1 = todayYear+"-"+todayMonth+"-"+todayDate;
        t1 = todayy1;
        
        today.add(Calendar.DAY_OF_MONTH, 7);
        
        String todayYear1 = Integer.toString(today.get(Calendar.YEAR));
        String todayMonth1 = Integer.toString(today.get(Calendar.MONTH)+1);
        String todayDate1 = Integer.toString(today.get(Calendar.DATE));
        
        String todayy2 = todayYear1+"-"+todayMonth1+"-"+todayDate1;
        t2 = todayy2;
        
        String gene2 = "select count(*) as 'field' from Project where pEndDate>('"+todayy1+"') and pEndDate<('"+todayy2+"') and pAvailability = 'YES' and pStatus = 'pending'";
   
        int num2=0;
      
        
        ResultSet count2 = db1.executeSQLQuery(gene2);
        
        try
        {
            if(count2.next())
            {
                num2 += Integer.parseInt(count2.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        jLabel12.setText(Integer.toString(num2));
        
        
        //next week projects
        
        today.add(Calendar.DAY_OF_MONTH, 7);
        
        String todayYear2 = Integer.toString(today.get(Calendar.YEAR));
        String todayMonth2 = Integer.toString(today.get(Calendar.MONTH)+1);
        String todayDate2 = Integer.toString(today.get(Calendar.DATE));
        
        String todayy3 = todayYear2+"-"+todayMonth2+"-"+todayDate2;
        t3 = todayy3;
        
        //get next week
        
        String gene3 = "select count(*) as 'field' from Project where pEndDate>('"+todayy2+"') and pEndDate<('"+todayy3+"') and pAvailability = 'YES' and pStatus = 'pending'";
   
        int num3=0;
      
        
        ResultSet count3 = db1.executeSQLQuery(gene3);
        
        try
        {
            if(count3.next())
            {
                num3 += Integer.parseInt(count3.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        jLabel16.setText(Integer.toString(num3));
        
        
        //get this month

        Calendar thisMonth1 = new GregorianCalendar();
        
        
        String thisMonthYear1 = Integer.toString(today.get(Calendar.YEAR));
        String thisMonthMonth1 = Integer.toString(today.get(Calendar.MONTH));
        String thisMonthDate1 = Integer.toString(1);
        
        String thisMonthh1 = thisMonthYear1+"-"+thisMonthMonth1+"-"+thisMonthDate1;
        m1 = thisMonthh1;
                
        
        today.add(Calendar.MONTH, 1);
        
        String thisMonthYear2 = Integer.toString(today.get(Calendar.YEAR));
        String thisMonthMonth2 = Integer.toString(today.get(Calendar.MONTH));
        String thisMonthDate2 = Integer.toString(1);
        
        String thisMonthh2 = thisMonthYear2+"-"+thisMonthMonth2+"-"+thisMonthDate2;
        m2 = thisMonthh2;
        
        
        String gene4 = "select count(*) as 'field' from Project where pEndDate>('"+thisMonthh1+"') and pEndDate<('"+thisMonthh2+"') and pAvailability = 'YES' and pStatus = 'pending'";
   
        int num4=0;
      
        
        ResultSet count4 = db1.executeSQLQuery(gene4);
        
        try
        {
            if(count4.next())
            {
                num4 += Integer.parseInt(count4.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        jLabel18.setText(Integer.toString(num4));
        
        //next month projects
        
        today.add(Calendar.MONTH, 1);
        
        String thisMonthYear3 = Integer.toString(today.get(Calendar.YEAR));
        String thisMonthMonth3 = Integer.toString(today.get(Calendar.MONTH));
        String thisMonthDate3 = Integer.toString(1);
        
        String thisMonthh3 = thisMonthYear3+"-"+thisMonthMonth3+"-"+thisMonthDate3;
        m3 = thisMonthh3;
        
         String gene5 = "select count(*) as 'field' from Project where pEndDate>('"+thisMonthh2+"') and pEndDate<('"+thisMonthh3+"') and pAvailability = 'YES' and pStatus = 'pending'";
   
        int num5=0;
      
        
        ResultSet count5 = db1.executeSQLQuery(gene5);
        
        try
        {
            if(count5.next())
            {
                num5 += Integer.parseInt(count5.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
         jLabel20.setText(Integer.toString(num5));

        
       
        
          try {
            Thread.sleep(120000);
        } catch (InterruptedException ex) {
            Logger.getLogger(InterfaceProject.class.getName()).log(Level.SEVERE, null, ex);
        }
         
          Calendar calendar = new GregorianCalendar();
          calendar.add(Calendar.SECOND, 120);
          jLabel21.setText("Next Automatic Update @ "+ Integer.toString(calendar.getTime().getHours())+ " : " + Integer.toString(calendar.getTime().getMinutes()) + " : " + Integer.toString(calendar.getTime().getSeconds()) );
        }
            else
            {
                break;
            }
            
        }
        
      
        
    }
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        AddEditRemoveProjects one = new AddEditRemoveProjects();
                   one.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        AddEditRemoveSuppliers one = new AddEditRemoveSuppliers();
                   one.setVisible(true);
                   
        
                   
                   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        MarkProject one = new MarkProject();
                   one.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        SearchProject one = new SearchProject();
                   one.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        ViewProjects one = new ViewProjects();
                   one.setVisible(true);
                   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        //get pending jobs
        
        
        String gene = "select count(*) as 'field' from project where pStatus='pending' and pAvailability='YES'";
   
        int num=0;
      
        
        ResultSet count13 = db1.executeSQLQuery(gene);
        
        try
        {
            if(count13.next())
            {
                num += Integer.parseInt(count13.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        this.jLabel4.setText(Integer.toString(num));
        
        
        //get finished jobs
        
        String gene1 = "select count(*) as 'field' from project where pStatus='finished' and pAvailability='YES'";
   
        int num1=0;
      
        
        ResultSet count1 = db1.executeSQLQuery(gene1);
        
        try
        {
            if(count1.next())
            {
                num1 += Integer.parseInt(count1.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        this.jLabel10.setText(Integer.toString(num1));
        
        
        //this week projects
        
        Calendar today = new GregorianCalendar();
        
        
        String todayYear = Integer.toString(today.get(Calendar.YEAR));
        String todayMonth = Integer.toString(today.get(Calendar.MONTH)+1);
        String todayDate = Integer.toString(today.get(Calendar.DATE));
        
        String todayy1 = todayYear+"-"+todayMonth+"-"+todayDate;
        
        today.add(Calendar.DAY_OF_MONTH, 7);
        
        String todayYear1 = Integer.toString(today.get(Calendar.YEAR));
        String todayMonth1 = Integer.toString(today.get(Calendar.MONTH)+1);
        String todayDate1 = Integer.toString(today.get(Calendar.DATE));
        
        String todayy2 = todayYear1+"-"+todayMonth1+"-"+todayDate1;
        
        String gene2 = "select count(*) as 'field' from Project where pEndDate>('"+todayy1+"') and pEndDate<('"+todayy2+"') and pAvailability = 'YES' and pStatus = 'pending'";
   
        int num2=0;
      
        
        ResultSet count2 = db1.executeSQLQuery(gene2);
        
        try
        {
            if(count2.next())
            {
                num2 += Integer.parseInt(count2.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD!", 1);
        }
        
        this.jLabel12.setText(Integer.toString(num2));
        
        
        //next week projects
        
        today.add(Calendar.DAY_OF_MONTH, 7);
        
        String todayYear2 = Integer.toString(today.get(Calendar.YEAR));
        String todayMonth2 = Integer.toString(today.get(Calendar.MONTH)+1);
        String todayDate2 = Integer.toString(today.get(Calendar.DATE));
        
        String todayy3 = todayYear2+"-"+todayMonth2+"-"+todayDate2;
        
        //get next week
        
        String gene3 = "select count(*) as 'field' from Project where pEndDate>('"+todayy2+"') and pEndDate<('"+todayy3+"') and pAvailability = 'YES' and pStatus = 'pending'";
   
        int num3=0;
      
        
        ResultSet count3 = db1.executeSQLQuery(gene3);
        
        try
        {
            if(count3.next())
            {
                num3 += Integer.parseInt(count3.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        this.jLabel16.setText(Integer.toString(num3));
        
        
        //get this month

        Calendar thisMonth1 = new GregorianCalendar();
        
        
        String thisMonthYear1 = Integer.toString(today.get(Calendar.YEAR));
        String thisMonthMonth1 = Integer.toString(today.get(Calendar.MONTH));
        String thisMonthDate1 = Integer.toString(1);
        
        String thisMonthh1 = thisMonthYear1+"-"+thisMonthMonth1+"-"+thisMonthDate1;
        
        today.add(Calendar.MONTH, 1);
        
        String thisMonthYear2 = Integer.toString(today.get(Calendar.YEAR));
        String thisMonthMonth2 = Integer.toString(today.get(Calendar.MONTH));
        String thisMonthDate2 = Integer.toString(1);
        
        String thisMonthh2 = thisMonthYear2+"-"+thisMonthMonth2+"-"+thisMonthDate2;
        
        
        String gene4 = "select count(*) as 'field' from Project where pEndDate>('"+thisMonthh1+"') and pEndDate<('"+thisMonthh2+"') and pAvailability = 'YES' and pStatus = 'pending'";
   
        int num4=0;
      
        
        ResultSet count4 = db1.executeSQLQuery(gene4);
        
        try
        {
            if(count4.next())
            {
                num4 += Integer.parseInt(count4.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD!", 1);
        }
        
        this.jLabel18.setText(Integer.toString(num4));
        
        //next month projects
        
        today.add(Calendar.MONTH, 1);
        
        String thisMonthYear3 = Integer.toString(today.get(Calendar.YEAR));
        String thisMonthMonth3 = Integer.toString(today.get(Calendar.MONTH));
        String thisMonthDate3 = Integer.toString(1);
        
        String thisMonthh3 = thisMonthYear3+"-"+thisMonthMonth3+"-"+thisMonthDate3;
        
         String gene5 = "select count(*) as 'field' from Project where pEndDate>('"+thisMonthh2+"') and pEndDate<('"+thisMonthh3+"') and pAvailability = 'YES' and pStatus = 'pending'";
   
        int num5=0;
      
        
        ResultSet count5 = db1.executeSQLQuery(gene5);
        
        try
        {
            if(count5.next())
            {
                num5 += Integer.parseInt(count5.getString("field"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(),"METROPOLITAN ENGINEERING (PVT) LTD", 1);
        }
        
        this.jLabel20.setText(Integer.toString(num5));

        
       
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        // TODO add your handling code here:
        
        this.jLabel19.setBackground(Color.red);
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel19ComponentRemoved
        // TODO add your handling code here:
        
        this.jLabel19.setBackground(Color.red);
    }//GEN-LAST:event_jLabel19ComponentRemoved

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        this.jLabel19.setBackground(Color.red);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String x = "select pID as 'Project ID', pName as 'Project', pSdate as 'Start Date', pEndDate as 'End Date' from project where pStatus='pending' and pAvailability='YES'";
        
        staticData.setTempProjectData(x);
        statViewProjects ss = new statViewProjects();
        ss.setVisible(true);
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
         String x = "select pID as 'Project ID', pName as 'Project', pSdate as 'Start Date', pEndDate as 'End Date' from project where pStatus='finished' and pAvailability='YES'";

        staticData.setTempProjectData(x);
        statViewProjects ss = new statViewProjects();
        ss.setVisible(true);
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
         String x = "select pID as 'Project ID', pName as 'Project', pSdate as 'Start Date', pEndDate as 'End Date' from Project where pEndDate>('"+t1+"') and pEndDate<('"+t2+"') and pAvailability = 'YES' and pStatus = 'pending'";

        staticData.setTempProjectData(x);
        statViewProjects ss = new statViewProjects();
        ss.setVisible(true);
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
        String x = "select pID as 'Project ID', pName as 'Project', pSdate as 'Start Date', pEndDate as 'End Date' from Project where pEndDate>('"+t2+"') and pEndDate<('"+t3+"') and pAvailability = 'YES' and pStatus = 'pending'";

        staticData.setTempProjectData(x);
        statViewProjects ss = new statViewProjects();
        ss.setVisible(true);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        String x = "select pID as 'Project ID', pName as 'Project', pSdate as 'Start Date', pEndDate as 'End Date' from Project where pEndDate>('"+m1+"') and pEndDate<('"+m2+"') and pAvailability = 'YES' and pStatus = 'pending'";

        staticData.setTempProjectData(x);
        statViewProjects ss = new statViewProjects();
        ss.setVisible(true);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        String x = "select pID as 'Project ID', pName as 'Project', pSdate as 'Start Date', pEndDate as 'End Date' from Project where pEndDate>('"+m2+"') and pEndDate<('"+m3+"') and pAvailability = 'YES' and pStatus = 'pending'";

        staticData.setTempProjectData(x);
        statViewProjects ss = new statViewProjects();
        ss.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        status=false;
        
        if (Data.Login.getPre_UI_type() == 1 || Data.Login.getPre_UI_type() == 2) {
            animation_exit a = new animation_exit();
            a.start();
            try {
                a.join();
            } catch (InterruptedException ex) {
                
            }
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        status=false;
        
        
        
    }//GEN-LAST:event_formWindowClosed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        
        GUI_Product.InterfaceProduct n = new GUI_Product.InterfaceProduct();
        n.setVisible(true);
        
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceProject().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
